### ISSUE TITLE
Add vibration reading 

### ISSUE THREAD

**Issue by thaus88** [assisi/assisipy#94]
Implement vibration reading method to acquire amplitude and frequency of the measured vibrations.

**Comment by dmiklic** [comment]
New device name: Fft

- implement Python code to handle
- update docs (assisipy communication protocol)

**Comment by dmiklic** [comment]
Closed by:

- 2e809d7a313b9013e56dc4e710799cc7ba38f375 (code)
- ac0a3449a55cbd77ed5e0985e28d2980d3fb1547 (doc update)
